name:                futharkBicubicScale
version:             0.1.0.0
github:              "githubuser/futharkBicubicScale"
license:             BSD3
author:              "Author name here"
maintainer:          "ianmbloom@gmail.com"
copyright:           "2020 Ian Bloom"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/futharkShuffle#readme>

dependencies:
- base
- transformers
- transformers-base
- containers
- mtl
- monad-control
- bytestring
- lens
- exceptions
# Needed by futhask
- massiv    >= 1.0.0.0
- massiv-io >= 1.0.0.1
- deepseq
# - OpenCL
- cuda

library:
  source-dirs: src
  c-sources: fut/entries.c
  include-dirs: /opt/cuda/include
  extra-lib-dirs: /opt/cuda/lib
  extra-libraries: cuda cudart nvrtc OpenCL

executables:
  test-scale:
    main:                Main.hs
    source-dirs:         test/bicubic-scale
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futharkBicubicScale
